# Generated by Django 5.1.1 on 2024-09-15 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64)),
                ("firstName", models.CharField(max_length=32)),
                ("lastName", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=64)),
                ("emailAddress", models.EmailField(max_length=64)),
                ("battlePass", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gameMode", models.CharField(max_length=64)),
                ("wpm", models.PositiveIntegerField()),
                ("accuracy", models.PositiveIntegerField()),
                ("lettersMissed", models.JSONField(blank=True, default=dict)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.accounts"
                    ),
                ),
            ],
        ),
    ]
