# Generated by Django 5.1.1 on 2024-09-16 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("typetest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistics",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="typetest.accounts"
            ),
        ),
        migrations.DeleteModel(
            name="Accounts",
        ),
    ]
