# Generated by Django 5.1.1 on 2024-09-19 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typetest', '0002_alter_statistics_username_delete_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('emailAddress', models.EmailField(max_length=64)),
                ('battlePass', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='statistics',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typetest.accounts'),
        ),
    ]
