# Generated by Django 5.1.1 on 2024-11-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("typetest", "0002_minigamestatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="minigamestatistics",
            name="obstacleBestTime",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
