# Generated by Django 5.1.1 on 2024-12-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typetest', '0003_minigamestatistics_obstaclebesttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
