# Generated by Django 5.1.1 on 2024-12-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typetest', '0004_account_level_account_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='xp',
            field=models.IntegerField(default=0, max_length=7500),
        ),
    ]
