# Generated by Django 5.1.1 on 2024-09-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("typetest", "0004_alter_accounts_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="profilePicture",
            field=models.ImageField(default=None, upload_to="images/"),
        ),
    ]
