# Generated by Django 5.1.1 on 2024-12-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typetest', '0005_alter_account_level_alter_account_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
