# Generated by Django 5.1.1 on 2024-09-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("typetest", "0005_accounts_profilepicture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="profilePicture",
            field=models.ImageField(default=None, null=True, upload_to="images/"),
        ),
    ]
