# Generated by Django 5.1.1 on 2024-12-04 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typetest', '0006_alter_account_level_alter_account_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquippedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.CharField(default='default')),
                ('snowSlopeAvatar', models.CharField(default='default')),
                ('snowSlopeObstacle1', models.BooleanField(default=False)),
                ('snowSlopeObstacle2', models.BooleanField(default=False)),
                ('snowSlopeObstacle3', models.BooleanField(default=False)),
                ('snowFallBackgrounf', models.CharField(default='default')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
