# Generated by Django 5.1.1 on 2024-12-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typetest', '0007_equippeditems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equippeditems',
            old_name='snowFallBackgrounf',
            new_name='snowFallBackground',
        ),
    ]
