# Generated by Django 5.1.1 on 2024-10-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typetest', '0007_alter_accounts_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
