# Generated by Django 5.1.1 on 2024-12-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typetest', '0008_rename_snowfallbackgrounf_equippeditems_snowfallbackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='equippeditems',
            name='character',
            field=models.CharField(default='bear'),
        ),
    ]
