# Generated by Django 5.1.1 on 2024-10-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typetest', '0009_customuser_remove_accounts_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='emailAddress',
            field=models.EmailField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
