# Generated by Django 5.1.1 on 2024-12-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typetest', '0009_equippeditems_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equippeditems',
            name='character',
            field=models.CharField(default='paul'),
        ),
    ]
