# Generated by Django 5.1.1 on 2024-10-10 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("typetest", "0010_customuser_is_staff_alter_customuser_emailaddress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistics",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
